apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
  template:
    metadata:
      labels:
        app: mern
    spec:
      containers:
        - name: mern-app
          image: mern-crud-app:latest  # Imagen local en Minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
            - name: NODE_ENV
              value: "production"
