apiVersion: v1
kind: Service
metadata:
  name: mern-service
spec:
  type: NodePort
  selector:
    app: mern
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30080
